headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/kiron/Desktop/legacy compass/legacy-compass-complete-working 4"
publishOrigin = "config"

[build.environment]
VITE_SUPABASE_URL = "https://kfomddpbpsaplyucodli.supabase.co"
VITE_MAPBOX_TOKEN = "pk.eyJ1IjoibGVnYWN5Y29tcGFzcyIsImEiOiJjbWV5MTNkMDAwdGR2Mm1vZTdtNmo4Nm5mIn0.wnWv7lPl2HNZNI8hmUvb1A"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(self), microphone=(), camera=()"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net https://api.mapbox.com https://api.tiles.mapbox.com https://cdn.supabase.com blob:; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://api.mapbox.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; connect-src 'self' https://api.mapbox.com https://events.mapbox.com https://*.tiles.mapbox.com https://*.supabase.co wss://*.supabase.co; worker-src blob: 'self'"

[[redirects]]
from = "/api/*"
to = "https://your-ghost-backend.com/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/jeff"
to = "/index.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-User-Profile = "jeff"

[[redirects]]
from = "/anna"
to = "/index.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-User-Profile = "anna"

[[redirects]]
from = "/les"
to = "/index.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-User-Profile = "les"